name: youtube_player_iframe
description: Flutter port of the official YouTube iFrame player API. Supports web & mobile platforms.
version: 4.0.3
repository: https://github.com/sarbagyastha/youtube_player_flutter
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_iframe

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.1
  webview_flutter_android: ^3.7.1
  webview_flutter_wkwebview: ^3.4.4
  url_launcher: ^6.1.11
  youtube_player_iframe_web: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/player.html

  plugin:
    platforms:
      web:
        default_package: youtube_player_iframe_web
